### ISSUE TITLE
Get-Token error in moving Crowdstrike CID

### ISSUE THREAD

**Issue by ninja-comprised-given** [amjcyber/crowdstrike#1]
Hello,
Getting below error when using the Crowdstrike CID change script. Have changed to a new api credential for both source & destination, have full rights to both api users. Tried in the latest and N-1 powershell as well.

Any ideas ?

```
Downloads\PowerShell-7.2.5-win-x64> Invoke-FalconRtr -Command runscript -Arguments "-CloudFile='UnknownFileName_2022-08-13T21:15:40Z.txt' -Timeout='600'" -HostId 11345ba1c7cd49fb5340c3d3e0abd78y

 

aid              : 11345ba1c7cd49fb5340c3d3e0abd78y

batch_id         : 22338f19-0eef-4687-baf6-eb6d6516a711

cloud_request_id : 0f66ffc4-5d05-4066-999f-a844806564g3

complete         : True

offline_queued   : False

session_id       : 98kf90a9-9004-43a5-9f99-25700cd6b558

stderr           : Unable to request token from source cloud US using client id (destination api username). Return was: System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.

                      at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)

                      at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
```

**Comment by amjcyber** [comment]
Hi there!
The error seems to be related with the authentication process: `Unable to request token...`
Try first to request a token to see if you can connect: `Request-FalconToken -ClientId 'client_id' -ClientSecret 'client_secret'`

**Comment by ninja-comprised-given** [comment]
I am able to request the token, any other suggestions ?

**Comment by amjcyber** [comment]
Make sure you are using the right Cloud (US, EU...) the error message is related with authentication.

**Comment by nikochal88** [comment]
Hello,

I am running the script through RTR I don't get any error messages. The script just remains at 
"[27364] 'cmd' beginning removal; sensor will become unresponsive..."

Nevertheless, the session / host does not seem to become unresponsive as I can continue to type.
Any idea on what the issue might be or like someone had the same behavior and needed to add/remove something?

PS. I did not put something on the $Hash = '', $Proxy = '' parameter.

Thanks, in advance.

![image](https://user-images.githubusercontent.com/123934118/227196215-a61de14c-ab4e-42d0-b54b-607e728f6a52.png)
